### ISSUE TITLE
x86 issues

### ISSUE THREAD

**Issue by v-nikulichev** [tbricks/tbstack#17]
There are problems on 32-bit OpenSUSE.

1) If `SYS_process_vm_readv`/`__NR_process_vm_readv` is not defined, we define it to `310` which seemed to be acceptable solution when target architecture was only x86-64. We should either require fresh kernel headers or add architecture-specific definitions for other architectures.

2) `offset` argument of `pread()` has signed type `off_t` and has size of 4 bytes on x86. However, large file support is enabled and `pread64()` is used actually. It results in integer overflow for higher addresses. We should check `_FILE_OFFSET_BITS` or `_LARGEFILE64_SOURCE`. @tylerwhall could you please advise? Are systems on x86/arm without large file support widely used in embedded? If not, moving onto `off64_t`/`pread64()` with additional check in autotools would be enough so far.

**Comment by tylerwhall** [comment]
> We should either require fresh kernel headers or add architecture-specific definitions for other architectures.

Yes, I think we should at least make sure the definition only applies to the relevant architecture. I would be ok with an explicit build failure if it's undefined, and only providing definitions for only x86/x86-64 to cover non-embedded users. A configure test to disable `SYS_process_vm_readv` if undefined is probably the most robust, but an explicit build failure is still an improvement.

I suppose I didn't see these issues on 32-bit x86/arm due to having a recent kernel and kernel headers which skipped the /proc/pid/mem path. It seems pread could be broken on any 32-bit architecture.

I think it's safe to require LFS everywhere by adding `AC_SYS_LARGEFILE` to the configure script. It seems glibc has supported this since 1999 or so, and musl only supports large files. uClibc makes it a config option, but the project seems mostly abandoned. Still, somone configuring their system to remove LFS should be able to recognize the build failure.

**Comment by v-nikulichev** [comment]
Created https://github.com/tbricks/tbstack/pull/21.

**Comment by v-nikulichev** [comment]
Fixed now.
